apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: tesx
spec:
  type: ClusterIP
  selector:
    app: mysql-db
  ports:
    - protocol: TCP
      port: 3306       # Serviceが公開するポート
      targetPort: 3306 # Podのポート
