apiVersion: v1
kind: Service
metadata:
  name: pm-service
  namespace: tesx
spec:
  type: ClusterIP
  selector:
    app: pm-app
  ports:
    - protocol: TCP
      port: 8081       # Serviceが公開するポート
      targetPort: 8081 # Podのポート
